### ISSUE TITLE
java.io.UncheckedIOException happens

### ISSUE THREAD

**Issue by YoshikiHigo** [kusumotolab/FinerGit#117]
下記の実行で，UncheckedIOExceptionが発生する
対象：https://github.com/eclipse/jgit
引数：--src と --des を指定

```sh
java.io.UncheckedIOException: org.eclipse.jgit.errors.IncorrectObjectTypeException: Object fd608fbe625a2b456d9f15c2b1dc41f252057dd7 is not a commit.
	at jp.ac.titech.c.se.stein.core.Try.io(Try.java:30)
	at jp.ac.titech.c.se.stein.core.RepositoryRewriter.prepareRevisionWalk(RepositoryRewriter.java:76)
	at jp.ac.titech.c.se.stein.core.ConcurrentRepositoryRewriter.rewriteTreesConcurrently(ConcurrentRepositoryRewriter.java:64)
	at jp.ac.titech.c.se.stein.core.ConcurrentRepositoryRewriter.rewriteCommits(ConcurrentRepositoryRewriter.java:53)
	at jp.ac.titech.c.se.stein.core.RepositoryRewriter.rewrite(RepositoryRewriter.java:42)
	at finergit.TreeRewriteFinerRepoBuilder.exec(TreeRewriteFinerRepoBuilder.java:42)
	at finergit.FinerGitMain.exec(FinerGitMain.java:65)
	at finergit.FinerGitMain.main(FinerGitMain.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at finergit.JarEntryPoint.main(JarEntryPoint.java:21)
Caused by: org.eclipse.jgit.errors.IncorrectObjectTypeException: Object fd608fbe625a2b456d9f15c2b1dc41f252057dd7 is not a commit.
	at org.eclipse.jgit.revwalk.RevWalk.parseCommit(RevWalk.java:801)
	at jp.ac.titech.c.se.stein.core.RepositoryRewriter.lambda$0(RepositoryRewriter.java:78)
	at jp.ac.titech.c.se.stein.core.Try.io(Try.java:28)
	... 12 more
2018-12-11 00:03:05 [INFO]  FinerGitMain - elapsed time: 1 seconds
```

**Comment by sh5i** [comment]
再現しました．commit ではなく blob を指しているタグを扱えていないのが原因です．
commit を指さないタグは無視するようにします．

**Comment by sh5i** [comment]
https://github.com/sh5i/git-stein/commit/b2a64e777c9188180e336c44c47362564dc9263c で直しました．マージはちょっと待って下さい．
