### ISSUE TITLE
org.eclipse.jgit.api.errors.CheckoutConflictException happens in Mac

### ISSUE THREAD

**Issue by YoshikiHigo** [kusumotolab/FinerGit#126]
対象：https://github.com/zxing/zxing
コマンド：git fg --src zxing.git --des zxing.fg
```
> git fg --src zxing.git --des zxing.fg
org.eclipse.jgit.api.errors.CheckoutConflictException: Checkout conflict with file: Cannot delete file: /Users/higo/Data/tmp/zxing.fg/.github
	at org.eclipse.jgit.api.ResetCommand.checkoutIndex(ResetCommand.java:449)
	at org.eclipse.jgit.api.ResetCommand.call(ResetCommand.java:215)
	at finergit.GitRepo.resetHard(GitRepo.java:488)
	at finergit.TreeRewriteFinerRepoBuilder.exec(TreeRewriteFinerRepoBuilder.java:45)
	at finergit.FinerGitMain.exec(FinerGitMain.java:65)
	at finergit.FinerGitMain.main(FinerGitMain.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at finergit.JarEntryPoint.main(JarEntryPoint.java:21)
Caused by: org.eclipse.jgit.errors.CheckoutConflictException: Checkout conflict with file: Cannot delete file: /Users/higo/Data/tmp/zxing.fg/.github
	at org.eclipse.jgit.dircache.DirCacheCheckout.cleanUpConflicts(DirCacheCheckout.java:1282)
	at org.eclipse.jgit.dircache.DirCacheCheckout.doCheckout(DirCacheCheckout.java:518)
	at org.eclipse.jgit.dircache.DirCacheCheckout.checkout(DirCacheCheckout.java:484)
	at org.eclipse.jgit.api.ResetCommand.checkoutIndex(ResetCommand.java:447)
	... 10 more
```

**Comment by sh5i** [comment]
再現しました．コミットされていない（子を持つ）ディレクトリをクリーンアップできないという jgit のバグだと思います．以下のコメントを見る限り，認識はされているようです．
https://github.com/eclipse/jgit/blob/master/org.eclipse.jgit/src/org/eclipse/jgit/dircache/DirCacheCheckout.java#L1271

**Comment by YoshikiHigo** [comment]
あー，そうなんですね，どうしようかな..

**Comment by sh5i** [comment]
#114 同様，git コマンドを使えば正しく動きます．
Java 層で解決する場合，正攻法（本家を直す）以外の workaround としては，この例外が上がってきたときに，ディレクトリを消して再挑戦することはできると思います．

**Comment by sh5i** [comment]
あるいは，ファイルをすべて消した状態から始めるという方法もあるかもしれません．

**Comment by YoshikiHigo** [comment]
とりあえずの対処として，そのエラーが起こった場合には手動で git reset --hard と git clean をすることにします．例の100のプロジェクトで数個程度だったので．

**Comment by YoshikiHigo** [comment]
現在の環境（Windows 11，JGit 7.7.1，FinerGit master 08fab28）で再現実験を行いました．追跡済みファイル（`.github/a.md`）・未追跡ファイル（`.github/junk.txt`）・無視対象ファイル（`.github/x.log`）を含む `.github` ディレクトリが，`-p false` による書き換え後の HEAD から消える状況を作って変換したところ，`reset --hard` と `clean -fd` はいずれも成功し，`CheckoutConflictException` は再現しませんでした．報告当時の JGit（5 系）の不具合は，その後のバージョンで修正されていると考えられます．また，現在のコードでは reset / clean の失敗は警告として記録されるだけで，変換自体は中断しません．

現状 Windows で再現しなかったので close します．macOS などで再発した場合は再度開いてください．
