### ISSUE TITLE
hackpadでNoSuchFileException

### ISSUE THREAD

**Issue by YoshikiHigo** [kusumotolab/FinerGit#132]
NoSuchFileExceptionが発生する．

```
> java -jar FinerGit.jar finergit.FinerGitMain --src 131.hackpad.git --des 131.hackpad.fg
java.nio.file.NoSuchFileException: /Volumes/G-Drive/dataset/FinerGit-Exp-Borges185projects/131.hackpad.git/client/osx/Sparkle.framework/Versions/A/Resources/fr.lproj/fr.lproj
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:526)
	at sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:253)
	at java.nio.file.Files.copy(Files.java:1274)
	at finergit.FinerRepoBuilder$1.visitFile(FinerRepoBuilder.java:72)
	at finergit.FinerRepoBuilder$1.visitFile(FinerRepoBuilder.java:1)
	at java.nio.file.Files.walkFileTree(Files.java:2670)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at finergit.FinerRepoBuilder.copyDirectory(FinerRepoBuilder.java:60)
	at finergit.FinerRepoBuilder.exec(FinerRepoBuilder.java:32)
	at finergit.FinerGitMain.exec(FinerGitMain.java:65)
	at finergit.FinerGitMain.main(FinerGitMain.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at finergit.JarEntryPoint.main(JarEntryPoint.java:21)
```

**Comment by YoshikiHigo** [comment]
どうやら存在しないファイルへのシンボリックリンクの存在が原因っぽい
