### ISSUE TITLE
java.lang.IllegalArgumentException raised

### ISSUE THREAD

**Issue by sh5i** [kusumotolab/FinerGit#136]
Options: -o false -p false -t true --method-token-included false --token-type-included true
Target: https://github.com/JetBrains/kotlin
Commit: "8e54d78884e2c9d32535690457d27c277a567c1f"
Path: "/docs/exPuzzlers/src/_03_character/_14_Escape_Rout/EscapeRout.java"
```
Caused by: java.lang.IllegalArgumentException
	at org.eclipse.jdt.core.dom.StringLiteral.getLiteralValue(StringLiteral.java:218)
	at finergit.ast.JavaFileVisitor.visit(JavaFileVisitor.java:1611)
	at org.eclipse.jdt.core.dom.StringLiteral.accept0(StringLiteral.java:129)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2815)
...
	at org.eclipse.jdt.core.dom.CompilationUnit.accept0(CompilationUnit.java:258)
	at org.eclipse.jdt.core.dom.ASTNode.accept(ASTNode.java:2815)
	at finergit.ast.FinerJavaFileBuilder.getFinerJavaModules(FinerJavaFileBuilder.java:74)
	at finergit.FinerGitRewriter.extractFinerModules(FinerGitRewriter.java:71)
```

下記ファイルを対象にFinerModuleを抽出しようとしたときに出るようです．
https://github.com/JetBrains/kotlin/blob/8e54d78884e2c9d32535690457d27c277a567c1f/docs/exPuzzlers/src/_03_character/_14_Escape_Rout/EscapeRout.java

**Comment by sh5i** [comment]
Solved by https://github.com/kusumotolab/FinerGit/commit/6e1501f0e6922feadb044a3610e1df210e35d471
